# Site settings
title: Dan Carvajal
email: dan.v.carvajal@gmail.com
baseurl: "http://dancarvajal.github.io" # the subpath of your site, e.g. /blog/
url: "http://dancarvajal.github.io" # the base hostname & protocol for your site
description:      "Excpets from a unique person"

author:
  name:           Dan Carvajal
  email:          "dan.v.carvajal@gmail.com"
  uri:            "https://twitter.com/dan_v_c"
  twitter:        dan_v_c
  google_plus:    DanCarvajal
  github:         DanCarvajal
  linkedin:       DanCarvajal
  country:        United States

# Build settings
markdown: kramdown

paginate: 5
