# Site settings
title: Dan Carvajal
email: dan.v.carvajal@gmail.com
baseurl: ""
url: "http://dancarvajal.com" # the base hostname & protocol for your site
description:      "Excpets from a unique person"
locale:           en_us


author:
  name:           Dan Carvajal
  email:          "dan.v.carvajal@gmail.com"
  uri:            "https://twitter.com/dan_v_c"
  twitter:        dan_v_c
  google_plus:    DanCarvajal
  github:         DanCarvajal
  linkedin:       DanCarvajal
  country:        United States

# Open Graph
fb_admins:          http://facebook.com/dancarvajal
fb_appid:           508362279313777

# Build settings
markdown: kramdown

paginate_path: /page:num/
paginate:      5
